version: '3.8'

services:
  # Servicio de MongoDB
  mongo:
    image: mongo:latest
    container_name: encodergroup-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - encodergroup-network
    restart: unless-stopped

  # Servicio del backend (FastAPI)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: encodergroup-server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/encodergroup
      - ENVIRONMENT=production
      - JWT_SECRET=encodergroup_jwt_secret_key_secure_2023
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080  # 7 days
      - SMTP_HOST=mail.encodergroup.cl
      - SMTP_PORT=465
      - SMTP_USER=noreply@encodergroup.cl
      - SMTP_PASSWORD=.3H*qU8MI&?g
      - SMTP_SSL=true
      - SMTP_VERIFY_SSL=false
      - CLIENT_URL=http://localhost
      - ADMIN_EMAIL=admin@encodergroup.cl
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/app:/app/app
      - ./server/scripts:/app/scripts
      - ./server/uploads:/app/uploads
    networks:
      - encodergroup-network
    restart: unless-stopped

  # Servicio del frontend
  client:
    build:
      context: ./client-new
      dockerfile: Dockerfile
    container_name: encodergroup-client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - encodergroup-network
    restart: unless-stopped

# Volúmenes para persistencia de datos
volumes:
  mongo-data:

# Red para la comunicación entre servicios
networks:
  encodergroup-network:
    driver: bridge